# Generated by Django 3.0.5 on 2020-04-19 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('image_url', models.URLField(default='')),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=200)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=17.0, max_digits=5)),
                ('featured', models.BooleanField(default=False)),
                ('selling_counter', models.PositiveIntegerField(default=0)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('PR', 'preparing order'), ('OD', 'out for delivery'), ('DV', 'delivered'), ('PS', 'canceled'), ('NS', 'not submitted'), ('TS', 'test')], default='NS', max_length=30)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 11, 16, 897145, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='tshirt', max_length=50)),
                ('color', models.BooleanField(default=False)),
                ('size', models.BooleanField(default=False)),
                ('magic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorites', to='lazga_api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='N/A', max_length=50)),
                ('size', models.CharField(default='N/A', max_length=50)),
                ('magic', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lazga_api.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lazga_api.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='lazga_api.OrderItem', to='lazga_api.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lazga_api.Type'),
        ),
    ]
