# Generated by Django 3.0.5 on 2020-04-14 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RT', 'tshirt'), ('HD', 'hoodie'), ('MG', 'mug'), ('PS', 'popsocket'), ('PR', 'poster'), ('ST', 'sticker'), ('CR', 'coaster')], default='RT', max_length=2)),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=17.0, max_digits=5)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
