# Generated by Django 3.0.5 on 2020-04-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('RT', 'tshirt'), ('HD', 'hoodie'), ('MG', 'mug'), ('PS', 'popsocket'), ('PR', 'poster'), ('ST', 'sticker'), ('CR', 'coaster')], default='RT', max_length=2),
        ),
    ]
