# Generated by Django 3.0.5 on 2020-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
