# Generated by Django 3.0.5 on 2020-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=17.0, max_digits=5),
        ),
    ]
