# Generated by Django 3.0.5 on 2020-04-19 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 36, 40, 280283, tzinfo=utc)),
        ),
    ]
