# Generated by Django 3.0.5 on 2020-04-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_auto_20200414_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='itemPrice',
        ),
    ]
