# Generated by Django 3.0.5 on 2020-04-19 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_auto_20200420_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
