# Generated by Django 3.0.5 on 2020-04-14 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_item_itemprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
