# Generated by Django 3.0.5 on 2020-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(default='https://pbs.twimg.com/profile_images/1046609638425268224/-pJ9ZOS9_400x400.jpg'),
        ),
    ]
