# Generated by Django 3.0.5 on 2020-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_auto_20200417_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(default='tshirt', max_length=50),
        ),
    ]
