# Generated by Django 3.0.5 on 2020-04-19 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_auto_20200419_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 18, 46, 31, 529753)),
        ),
    ]
