# Generated by Django 3.0.5 on 2020-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0002_auto_20200417_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'preparing order'), ('OD', 'out for delivery'), ('DV', 'delivered'), ('PS', 'canceled'), ('NS', 'not submitted'), ('TS', 'test')], default='NS', max_length=30),
        ),
    ]
