# Generated by Django 3.0.5 on 2020-04-19 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0003_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 0, 3, 16, 186611)),
        ),
    ]
