# Generated by Django 3.0.5 on 2020-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0003_auto_20200417_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
