# Generated by Django 3.0.5 on 2020-04-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0003_auto_20200417_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
