# Generated by Django 3.0.5 on 2020-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0003_auto_20200414_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='price',
        ),
    ]
