# Generated by Django 3.0.5 on 2020-04-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0003_auto_20200417_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RT', 'tshirt'), ('HD', 'hoodie'), ('MG', 'mug'), ('PS', 'popsocket'), ('PR', 'poster'), ('ST', 'sticker'), ('CR', 'coaster'), ('LS', 'long sleeve')], default='RT', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lazga_api.Type'),
        ),
    ]
