# Generated by Django 3.0.5 on 2020-04-18 21:31

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lazga_api', '0005_auto_20200418_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='magic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='lazga_api.Item')),
            ],
        ),
    ]
