# Generated by Django 3.0.5 on 2020-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0007_auto_20200419_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to='lazga_api.Item'),
        ),
    ]
