# Generated by Django 3.0.5 on 2020-04-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0008_auto_20200419_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profiles',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lazga_api.Profile'),
        ),
    ]
