# Generated by Django 3.0.5 on 2020-04-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazga_api', '0009_item_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='profiles',
        ),
    ]
